"""initial create of tables

Revision ID: a1d170ac4268
Revises: 
Create Date: 2024-09-20 11:30:29.496184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1d170ac4268'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attachment_table',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('dev_table',
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STAFF', name='devrole'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_table',
    sa.Column('username', sa.String(length=16), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'USER', name='userrole'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('ticket_table',
    sa.Column('typ', sa.Enum('INC', 'RITM', name='typ'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'NEW', 'CLOSE', name='status'), nullable=False),
    sa.Column('state', sa.Enum('DRAFT', 'SUBMITTED', name='state'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity'), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('assign_to_id', sa.Uuid(), nullable=True),
    sa.Column('uid', sa.Uuid(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('update_date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['assign_to_id'], ['dev_table.uid'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['user_table.uid'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('uid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket_table')
    op.drop_table('user_table')
    op.drop_table('dev_table')
    op.drop_table('attachment_table')
    # ### end Alembic commands ###
